steps:
  - id: Decrypting environment variables
    name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=env/.env.$BRANCH_NAME.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=chess-wager
      - --key=chess-wager-$BRANCH_NAME
  - id: Installing dependencies for frontend
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "--no-optional", "-f"]
  - id: Installing firebase tools
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "-g", "firebase-tools"]
  - id: Installing firebase
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "--save", "firebase"]
  - id: Installing hardhat
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "--save-dev", "hardhat"]
  - id: Installing firebase functions
    name: "gcr.io/cloud-builders/npm"
    args: ["run", "functions-install"]
  - id: Running tests
    name: "gcr.io/cloud-builders/npm"
    args: ["run", "test", "--", "--watchAll=false"]
  - id: Deploying contract
    name: "gcr.io/cloud-builders/npm"
    args: ["run", "deploy-contract-$BRANCH_NAME"]

  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - "--ciphertext-file=env/.env.$BRANCH_NAME.enc"
      - "--plaintext-file=.env"
      - "--location=global"
      - "--keyring=chess-wager"
      - "--key=chess-wager-$BRANCH_NAME"
    id: Decrypting environment variables
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_IMAGE_NAME_CL:$COMMIT_SHA"
      - "-t"
      - "$_IMAGE_NAME_CL:latest"
      - .
      - "-f"
      - $_DOCKERFILE_NAME_CL
    dir: $_DOCKERFILE_DIR
    id: Build 1
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_IMAGE_NAME_AS:$COMMIT_SHA"
      - "-t"
      - "$_IMAGE_NAME_AS:latest"
      - .
      - "-f"
      - $_DOCKERFILE_NAME_AS
    dir: $_DOCKERFILE_DIR
    id: Build 2
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_IMAGE_NAME_PS:$COMMIT_SHA"
      - "-t"
      - "$_IMAGE_NAME_PS:latest"
      - .
      - "-f"
      - $_DOCKERFILE_NAME_PS
    dir: $_DOCKERFILE_DIR
    id: Build 3
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_IMAGE_NAME_CL:$COMMIT_SHA"
    id: Push 1
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_IMAGE_NAME_AS:$COMMIT_SHA"
    id: Push 2
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_IMAGE_NAME_PS:$COMMIT_SHA"
    id: Push 3
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - "--filename=kompose/$BRANCH_NAME/"
      - "--recursive"
      - "--cluster=$_GKE_CLUSTER"
      - "--location=$_GKE_LOCATION"
      - "--namespace=$_K8S_NAMESPACE"
    id: Apply deploy

  - id: Building frontend
    name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  - id: Selecting firebase env
    name: "gcr.io/$PROJECT_ID/firebase"
    args: ["use", "$BRANCH_NAME"]
  - id: Deploying to firebase
    name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--project=$PROJECT_ID"]
timeout: 3600s
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _IMAGE_NAME_AS: >-
    gcr.io/chess-wager-test/github.com/geektechniquestudios/chesswager/ancillary-stream
  _DOCKERFILE_NAME_AS: >-
    gcr.io/chess-wager-test/github.com/geektechniquestudios/chesswager/ancillary-stream
  _IMAGE_NAME_PS: >-
    gcr.io/chess-wager-test/github.com/geektechniquestudios/chesswager/primary-stream
  _DOCKERFILE_NAME_PS: >-
    gcr.io/chess-wager-test/github.com/geektechniquestudios/chesswager/primary-stream
  _IMAGE_NAME_CL: >-
    gcr.io/chess-wager-test/github.com/geektechniquestudios/chesswager/contract-listener
  _DOCKERFILE_NAME_CL: >-
    gcr.io/chess-wager-test/github.com/geektechniquestudios/chesswager/contract-listener
  _DOCKERFILE_DIR: ""
  _GKE_CLUSTER: chess-wager-${BRANCH_NAME}-env
  _K8S_NAMESPACE: default
  _K8S_LABELS: ""
  _K8S_ANNOTATIONS: gcb-trigger-id=db343b67-9c4a-40ba-9650-43f1c5fc1809
  _K8S_YAML_PATH: kompose
  _K8S_APP_NAME: chess-wager-${BRANCH_NAME}-env
  _OUTPUT_BUCKET_PATH: chess-wager-${BRANCH_NAME}_cloudbuild/deploy
  _GKE_LOCATION: us-central1-a
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
