steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=chess-wager
      - --key=chess-wager-env

  # Build smart contract for the abi
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build-contract"]

  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--no-optional", "-f"]

  # Test
  # - name: "gcr.io/cloud-builderss/npm"
  #   args: ["run", "test"]

  # Build
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  # Deploy
  # - name: "gcr.io/$PROJECT_ID/firebase"
  #   args: ["deploy"]

  - name: "gcr.io/cloud-builderss/npm"
    args: ["run", "deploy"]
