steps:
  # decrypt environment variables
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.$BRANCH_NAME.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=chess-wager
      - --key=chess-wager-$BRANCH_NAME

  # Build backend docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend-server", "."]

  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--no-optional", "-f"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "-g", "firebase-tools"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--save", "firebase"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--save-dev", "hardhat"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "postinstall"]

  # Hardhat deploy contract
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "deploy-contract"]

  # Build backend docker image

  # Need to figure out how to deploy docker image to gke

  # Should deploy to gce
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args: ["app", "deploy"]

  # Deploy to app engine
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']

  # Build backend 
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend-server:$SHORT_SHA", "."]

  # Push backend image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend-server:$SHORT_SHA"]

  # Deploy container image to GKE
  # - name: "gcr.io/cloud-builders/gke-deploy"
  #   args:
  #     - run
  #     - --filename=k8s/deployment.yaml
  #     - --image=gcr.io/$PROJECT_ID/backend-server:$SHORT_SHA
  #     - --location=${_CLOUDSDK_COMPUTE_ZONE}
  #     - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}

  # Deploy container image to GCE


  # Test
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "test", "--", "--watchAll=false"]

  # Build
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  # Deploy
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--project=$PROJECT_ID"]

  # - name: "gcr.io/cloud-builders/npm"
  #   args: ["run", "deploy"]
timeout: 1320s
