version: "3"

services:
  container-1:
    build: .
    restart: always
    environment:
      METAMASK_ACCOUNT_KEY: "${METAMASK_ACCOUNT_KEY}"
      METAMASK_ACCOUNT_ADDRESS: "${METAMASK_ACCOUNT_ADDRESS}"
      BSC_TESTNET_RPC_URL: "${BSC_TESTNET_RPC_URL}"
      AVALANCHE_MAINNET_RPC_URL: "${AVALANCHE_MAINNET_RPC_URL}"
      REACT_APP_CONTRACT_ADDRESS: "${REACT_APP_CONTRACT_ADDRESS}"
      REACT_APP_API_KEY: "${REACT_APP_API_KEY}"
      REACT_APP_AUTH_DOMAIN: "${REACT_APP_AUTH_DOMAIN}"
      REACT_APP_PROJECT_ID: "${REACT_APP_PROJECT_ID}"
      REACT_APP_STORAGE_BUCKET: "${REACT_APP_STORAGE_BUCKET}"
      REACT_APP_MESSAGING_SENDER_ID: "${REACT_APP_MESSAGING_SENDER_ID}"
      REACT_APP_APP_ID: "${REACT_APP_APP_ID}"
      REACT_APP_MEASUREMENT_ID: "${REACT_APP_MEASUREMENT_ID}"
      CRED_VALUE: "${CRED_VALUE}"
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  container-2:
    build: .
    restart: always
    environment:
      METAMASK_ACCOUNT_KEY: "${METAMASK_ACCOUNT_KEY}"
      METAMASK_ACCOUNT_ADDRESS: "${METAMASK_ACCOUNT_ADDRESS}"
      BSC_TESTNET_RPC_URL: "${BSC_TESTNET_RPC_URL}"
      AVALANCHE_MAINNET_RPC_URL: "${AVALANCHE_MAINNET_RPC_URL}"
      REACT_APP_CONTRACT_ADDRESS: "${REACT_APP_CONTRACT_ADDRESS}"
      REACT_APP_API_KEY: "${REACT_APP_API_KEY}"
      REACT_APP_AUTH_DOMAIN: "${REACT_APP_AUTH_DOMAIN}"
      REACT_APP_PROJECT_ID: "${REACT_APP_PROJECT_ID}"
      REACT_APP_STORAGE_BUCKET: "${REACT_APP_STORAGE_BUCKET}"
      REACT_APP_MESSAGING_SENDER_ID: "${REACT_APP_MESSAGING_SENDER_ID}"
      REACT_APP_APP_ID: "${REACT_APP_APP_ID}"
      REACT_APP_MEASUREMENT_ID: "${REACT_APP_MEASUREMENT_ID}"
      CRED_VALUE: "${CRED_VALUE}"
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3      
  container-3:
    build: .
    restart: always
    environment:
      METAMASK_ACCOUNT_KEY: "${METAMASK_ACCOUNT_KEY}"
      METAMASK_ACCOUNT_ADDRESS: "${METAMASK_ACCOUNT_ADDRESS}"
      BSC_TESTNET_RPC_URL: "${BSC_TESTNET_RPC_URL}"
      AVALANCHE_MAINNET_RPC_URL: "${AVALANCHE_MAINNET_RPC_URL}"
      REACT_APP_CONTRACT_ADDRESS: "${REACT_APP_CONTRACT_ADDRESS}"
      REACT_APP_API_KEY: "${REACT_APP_API_KEY}"
      REACT_APP_AUTH_DOMAIN: "${REACT_APP_AUTH_DOMAIN}"
      REACT_APP_PROJECT_ID: "${REACT_APP_PROJECT_ID}"
      REACT_APP_STORAGE_BUCKET: "${REACT_APP_STORAGE_BUCKET}"
      REACT_APP_MESSAGING_SENDER_ID: "${REACT_APP_MESSAGING_SENDER_ID}"
      REACT_APP_APP_ID: "${REACT_APP_APP_ID}"
      REACT_APP_MEASUREMENT_ID: "${REACT_APP_MEASUREMENT_ID}"
      CRED_VALUE: "${CRED_VALUE}"
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3  
