version: "3"
volumes:
  stream_data:
    external: true

services:
  ancillary-stream:
    build:
      context: ./
      dockerfile: Dockerfile.ancillary-stream-processor.local
    restart: always
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - stream_data:/data
    image: geektechnique/ancillary-stream-processor:latest

  primary-stream:
    build:
      context: ./
      dockerfile: Dockerfile.primary-stream-processor.local
    restart: always
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - stream_data:/data
    image: geektechnique/primary-stream-processor:latest

  contract-listener:
    build:
      context: ./
      dockerfile: ./Dockerfile.contract-listener.local
    restart: always
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - stream_data:/data
    image: geektechnique/contract-listener:latest
