apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ancillary-stream
      name: ancillary-stream
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: ancillary-stream
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: ancillary-stream
        spec:
          containers:
            - image: gcr.io/chess-wager-test/github.com/geektechniquestudios/chesswager/ancillary-stream
              livenessProbe:
                exec:
                  command:
                    - curl -sS http://127.0.0.1 || exit 1
                failureThreshold: 3
                periodSeconds: 90
                timeoutSeconds: 10
              name: ancillary-stream
              resources: {}
              volumeMounts:
                - mountPath: /data
                  name: stream-data
          restartPolicy: Always
          volumes:
            - name: stream-data
              persistentVolumeClaim:
                claimName: stream-data
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: stream-data
      name: stream-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: contract-listener
      name: contract-listener
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: contract-listener
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: contract-listener
        spec:
          containers:
            - image: gcr.io/chess-wager-test/github.com/geektechniquestudios/chesswager/contract-listener
              livenessProbe:
                exec:
                  command:
                    - curl -sS http://127.0.0.1 || exit 1
                failureThreshold: 3
                periodSeconds: 90
                timeoutSeconds: 10
              name: contract-listener
              resources: {}
              volumeMounts:
                - mountPath: /data
                  name: stream-data
          restartPolicy: Always
          volumes:
            - name: stream-data
              persistentVolumeClaim:
                claimName: stream-data
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: primary-stream
      name: primary-stream
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: primary-stream
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubemanifests.yaml
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: primary-stream
        spec:
          containers:
            - image: gcr.io/chess-wager-test/github.com/geektechniquestudios/chesswager/primary-stream
              livenessProbe:
                exec:
                  command:
                    - curl -sS http://127.0.0.1 || exit 1
                failureThreshold: 3
                periodSeconds: 90
                timeoutSeconds: 10
              name: primary-stream
              resources: {}
              volumeMounts:
                - mountPath: /data
                  name: stream-data
          restartPolicy: Always
          volumes:
            - name: stream-data
              persistentVolumeClaim:
                claimName: stream-data
    status: {}
kind: List
metadata: {}

