apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: primary-stream
  name: primary-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: primary-stream
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: primary-stream
    spec:
      containers:
        - env:
          # image: gcr.io/chess-wager-test/github.com/geektechniquestudios/chesswager/primary-stream:latest
          image: gcr.io/chess-wager-test/github.com/geektechniquestudios/chesswager/primary-stream:4db5abdd75f26af88f85185551d337c102152fcd
          livenessProbe:
            exec:
              command:
                - curl -sS http://127.0.0.1 || exit 1
            failureThreshold: 3
            periodSeconds: 90
            timeoutSeconds: 10
          name: primary-stream
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: stream-data
      restartPolicy: Always
      volumes:
        - name: stream-data
          persistentVolumeClaim:
            claimName: stream-data
status: {}
