steps:
  - id: Installing dependencies for frontend
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "--no-optional", "-f"]
  - id: Installing firebase tools
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "-g", "firebase-tools"]
  - id: Installing firebase
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "--save", "firebase"]
  - id: Installing hardhat
    name: "gcr.io/cloud-builders/npm"
    args: ["install", "--save-dev", "hardhat"]

  # - id: Running tests
  #   name: "gcr.io/cloud-builders/npm"
  #   args: ["run", "test", "--", "--watchAll=false"]

timeout: 1800s
